# Generated by Django 5.0 on 2024-01-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='website.color'),
        ),
    ]
