# Generated by Django 5.0 on 2024-01-05 15:31

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project_city_alter_productadvantage_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('notified', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[600, 600], upload_to='project/thumbnails/'),
        ),
    ]
